### ISSUE TITLE
Script not working when called from zabbix

### ISSUE THREAD

**Issue by eugenefeel** [moudsen/mailGraph#41] opened 2023-08-14 07:35 UTC
@moudsen Hello. I read this issue because i have problem with you project. When i exec cli test, I got email, but when i use button test or action in zabbix i have problem.
I noticed that eventid does not work.
Also in the action error I get the error
MailGraph notification failed : [MailGraph Webhook] Invalid duration? Integer required (set to zero if unknown)!
Help solve this problem
![](https://user-images.githubusercontent.com/139457476/260010582-11a2124c-1a43-408d-8f16-939e0bddd5a1.png)
![](https://user-images.githubusercontent.com/139457476/260011127-35a9df2e-f2fd-4be7-911f-7688a59a3e21.png)

**Comment by moudsen** [comment] 2023-08-15 19:58
Can you please share the log of MailGraph with me? (mark.oudsen@puzzl.nl or paste relevant part here after execution)
I need the log ifle for further analysis as this will likely provide a clue of what is happening in the background.

**Comment by eugenefeel** [comment] 2023-08-15 20:07
For some reason I am not getting a log from MailGraph when calling from zabbix

**Comment by moudsen** [comment] 2023-08-15 20:39
Very likely in that case the URL to mailGraph.php is incorrect.
Can you please make sure that the full http path to mailGraph.php is correct?

**Comment by eugenefeel** [comment] 2023-08-16 07:33
In truth, if my link was wrong, I wouldn't get the mailgraph.php error. What do you think about it?

**Comment by moudsen** [comment] 2023-08-16 08:51
The origin of the message says "MailGraph webhook", That is the Javascript that is part of the Zabbix media plugin. If you open "MailGraph" and look at the "Script" section, you will find the error there.
This means that the webhook does not even reach the actual mailGraph.php part (actually called just after the parameter check) hence my request to verify the "log" directory to verify that indeed the main script is not even called. Perhaps you already gave me that hint when stating "no logs where found".

When the Javascript part says "I do not have a value for 'duration'" something else is wrong perhaps during the setup/creation of the media type.

Can you share in which version of Zabbix you try to use mailGraph?

**Comment by moudsen** [comment] 2023-08-16 09:00
I think I have been able to re-produce the condition for this error. Please bear with me while I am analyzing the root cause.

**Comment by moudsen** [comment] 2023-08-16 09:07
Issue confirmed but no root cause yet (seems as if Zabbix does not pass the parameter at all if set to zero, but only occurs in Zabbix v5).
Can you please confirm your version of Zabbix?

**Comment by eugenefeel** [comment] 2023-08-16 09:14
Yes, you right. My version zabbix is 5.4.12.

**Comment by moudsen** [comment] 2023-08-16 09:36
Check. I am able to reproduce the issue in my 5.4 test environment and working on a solution for it as well as trying to find a better way to display the actual issue at hand instead of the JSON ERROR thrown. Needs some code rewrite, so please bear with me - will try to fix it today.

**Comment by eugenefeel** [comment] 2023-08-16 09:40
This so good news. Can i help you something?

**Comment by moudsen** [comment] 2023-08-16 10:49
I've fixed the issue at hand but refactoring some code to prevent the invalid JSON messages. Running and testing on my environment as we speak. Updates to Javascript (removed check of duration, better response handling) and mailGraph.php main code (removed check of duration).
Got "Missing DURATION" now from the script - fixed that already.

I need to test 2 more conditions and on Zabbix 6 before I can release the updates.

**Comment by eugenefeel** [comment] 2023-08-16 11:00
I think you're right. Maybe you can push change in the new branch and i can test your fix?

**Comment by moudsen** [comment] 2023-08-16 11:47
After I've finished the Zabbix 6 testing I will push v2.15 with the fixes.

**Comment by moudsen** [comment] 2023-08-16 12:19
v2.15 pushed to main.
You need to replace "mailGraph.php" and the Javascript inside the Media Type 'MailGraph' to test if this actually resolves the issues (or just remove and import the Media Type again).
Can you please test if this now also works for you?

**Comment by eugenefeel** [comment] 2023-08-16 14:42
Ok. I'll check it at night

**Comment by moudsen** [comment] 2023-08-16 14:44
Appreciated. Will hold with the release until verification is done at your end.

**Comment by moudsen** [comment] 2023-08-16 20:28
Running fine now within my environments and promoting the release. In case of any other issues feel free to post here. I'm also pushing v2.16 that contains the ability to include Action messages in the email right after v2.15.

**Comment by eugenefeel** [comment] 2023-08-16 21:36
Okay. I tested release 2.16 but i got new problem. Previos problem connected with wrong nginx config. 
![ScreenShot-2023-08-17](https://github.com/moudsen/mailGraph/assets/139457476/f74f8ef2-41cf-434e-a23e-1fee49a55686)

**Comment by eugenefeel** [comment] 2023-08-16 21:38
Okay. I tested release 2.16 but i got new problem. Previos problem connected with wrong nginx config. 
![ScreenShot-2023-08-17](https://github.com/moudsen/mailGraph/assets/139457476/a34a7615-aeed-4767-be82-8c703de240c6)

**Comment by moudsen** [comment] 2023-08-17 07:24
Did you create an "images" folder as per the installation instructions and did you give permissions for NGINX to access that path?
If you test with the CLI you are using mailGraph with the permissions of that particular user.
Once firing from within NGINX, mailGraph will use the NGINX permissions.
Can you please check at your end?

**Comment by eugenefeel** [comment] 2023-08-17 08:25
Yes I created image dir, i think it's connected with wrong nginx config

**Comment by eugenefeel** [comment] 2023-08-17 08:41
To tell the truth idk what is the wrong. I have image dir and i can get file but script not working. I'm using default zabbix nginx config and your script is where is zabbix frontend
![ScreenShot-2023-08-17](https://github.com/moudsen/mailGraph/assets/139457476/65985a9d-8289-4649-8b7e-727a4ed7f718)

**Comment by moudsen** [comment] 2023-08-17 10:41
Please
- install the latest mailGraph.php v2.16
- remove the current images directory ("rm -Rf images' within the directory of mailGraph.php)
- run a test from within Zabbix (not the CLI); this will create an images path with the correct credentials

Let me know if this works for you?

**Comment by eugenefeel** [comment] 2023-08-18 08:33
It doesn't work for me

**Comment by moudsen** [comment] 2023-08-18 08:45
Can you share a "ls -la" of the directory where mailGraph is installeren?

**Comment by eugenefeel** [comment] 2023-08-18 09:01
Yeah, shure
![ScreenShot-2023-08-18](https://github.com/moudsen/mailGraph/assets/139457476/2d782648-871a-4978-821f-d4b35be6f584)
If I start CLI test image directory will be create. I tested it

**Comment by moudsen** [comment] 2023-08-18 10:26
If you start with CLI, the owner of the CLI will be used to created the path.
If you start with Zabbix Mailgraph test, the owner will be the web server.
Your current setup is very unlikely to work as the NGINX owner is likely www-user or something similar. Should not be root in the first place.
You can find the current owner via `ps -ef | grep nginx` and taking a look at the process owner. Likely also something like www-user. This article, just as an example, explains the principles behind user/group ownership of a webserver: https://askubuntu.com/questions/873839/what-is-the-www-data-user.
You need to change the ownership very likely with `chown www-user *` to allow mailGraph to function from within the webserver.

Again, mailGraph will created LOG, IMAGES and TMP for you, so the easy option is to remove LOG, TMP and IMAGES and have mailGraph run via Zabbix media test. That should create the directories with the right ownership.

**Comment by eugenefeel** [comment] 2023-08-18 10:33
Hmmm, great idea. I'll check it now

**Comment by eugenefeel** [comment] 2023-08-18 10:44
Yes, you was right. I got message with graph
![ScreenShot-2023-08-18](https://github.com/moudsen/mailGraph/assets/139457476/a6e48eaa-60a1-43db-8808-12547628d1e4)

**Comment by moudsen** [comment] 2023-08-18 11:01
Success!
Closing this issue now. In case of any new ones do not hesitate to raise a new request.

**Closed as completed by moudsen** 2023-08-18 11:01 UTC
Labels: bug, documentation, Fixed!, Installation Assistance, v2.x, Configuration issue, Verified Zabbix 5.4, Verified Zabbix 6.0 LTS
